services:
  mongodb:
    image: mongo
    container_name: mongo-city-db

    environment:
      MONGO_INITDB_DATABASE: citydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - mongo_network

  mongo-express:
    restart: always
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

    ports:
      - '8081:8081'
    volumes:
      - mongo_express_volume:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
volumes:
  mongo_data:
      driver: local
  mongo_express_volume: